# Generated by Django 3.1.4 on 2021-01-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=20)),
                ('your_mail', models.CharField(max_length=20)),
                ('your_subject', models.CharField(max_length=20)),
                ('your_message', models.TextField()),
            ],
        ),
    ]
